export const DISPOSABLE_DOMAINS = [
  "10minutemail.com", "10minutemail.net", "33mail.com", "airmail.cc", "anonbox.net",
  "antichef.com", "antichef.net", "brefmail.com", "burntmail.com", "ce.mintemail.com",
  "clrmail.com", "cool.fr.nf", "courriel.fr.nf", "cust.tele2.co.uk", "dayrep.com",
  "deadaddress.com", "discard.email", "discardmail.com", "discardmail.de", "dispo.cc",
  "disposable.com", "dispostable.com", "dodgit.com", "drdrb.com", "eelmail.com",
  "einrot.com", "emailondeck.com", "emailtemporaneo.it", "fleckens.hu", "getairmail.com",
  "grr.la", "guerrillamail.biz", "guerrillamail.com", "guerrillamail.de", "guerrillamail.net",
  "guerrillamail.org", "guerrillamailblock.com", "gustido.com", "harakirimail.com",
  "hushmail.com", "imgof.com", "incognitomail.org", "inbox.lv", "inboxclean.com",
  "insorg-mail.info", "instant-mail.de", "jetable.fr", "jetable.org", "jourrapide.com",
  "kaffeehaus-oelde.de", "lcrealm.com", "letthemeatspam.com", "link2mail.net",
  "lortemail.dk", "mail-temporaire.fr", "mail.ru", "mailcatch.com", "maildrop.cc",
  "mailexpire.com", "mailforspam.com", "mailimate.com", "mailinator.com", "mailinator2.com",
  "mailnesia.com", "mailnull.com", "mailprox.com", "mailsac.com", "mailtemp.net",
  "mailtrash.net", "meltmail.com", "mintemail.com", "moakt.com", "mohmal.com",
  "my10minutemail.com", "mytrashmail.com", "mytrashmail.net", "nepwk.com", "noclickemail.com",
  "nomail.xl.cx", "nospam.today", "nospamfor.us", "notmail.net", "null.net", "o2.pl",
  "oneoffmail.com", "owlymail.com", "pookmail.com", "proxymail.eu", "pub.mintemail.com",
  "rhyta.com", "sags-per-mail.de", "sharklasers.com", "sibmail.com", "sofort-mail.de",
  "spam.la", "spam4.me", "spambob.com", "spambog.com", "spambox.us", "spamgourmet.com",
  "spamhole.com", "spammotel.com", "spammotel.net", "spamspot.com", "superrito.com",
  "teleworm.us", "temp-mail.org", "temp-mail.ru", "tempemail.net", "tempinbox.com",
  "tempmail.com", "tempmail.de", "tempmail.net", "tempmailaddress.com", "tempr.email",
  "throwawaymail.com", "trash-mail.com", "trashmail.com", "trashmail.net", "trashmail.org",
  "trbvm.com", "up.mintemail.com", "uroid.com", "wegwerfmail.de", "wegwerfmail.net",
  "wegwerfmail.org", "wh4f.org", "wuzup.net", "yilinxiang.com", "yopmail.com",
  "yopmail.fr", "yopmail.net", "zehnminutenmail.de"
];
